### ISSUE TITLE
First Tab saving broken

### ISSUE THREAD

**Issue by RichardMuri** [LanceFiondella/srt.core#30]
Tested using Chrome, Internet Explorer and Firefox. All four file types broken (PNG, JPG, PDF, TIFF). Using CSV of sample models in model testing folder, SYS1. IE returns a 500 error, I suspect a server issue. 
IE:
![image](https://cloud.githubusercontent.com/assets/11636785/21901933/e9d97d5e-d8c7-11e6-9a7b-eac746a5bdd3.png)

Chrome:
![image](https://cloud.githubusercontent.com/assets/11636785/21902009/3389c1e8-d8c8-11e6-9a55-b2b346f9dfcd.png)

**Comment by RichardMuri** [comment]
Note: saving the table instead of the plot appears to work.

**Comment by RichardMuri** [comment]
Same issue on second tab

**Comment by arhik** [comment]
@RichardMuri Thanks.
