### ISSUE TITLE
Unable to Upload xlsx

### ISSUE THREAD

**Issue by RichardMuri** [LanceFiondella/srt.core#31]
Unable to upload model_data.xlsx on Chrome: 

![image](https://cloud.githubusercontent.com/assets/11636785/21902110/aba2e330-d8c8-11e6-8d94-71e38b47829f.png)

model_data.csv appears to work fine.

**Comment by arhik** [comment]
Memory is full. May be we should remove other applications we don't use and clean uploaded data.

**Comment by vshekar** [comment]
I had this issue last week as well. I used certain commands to remove stopped docker containers and dangling images which freed up 40% of the space. I had also removed a number of unwanted applications maybe there might be more? But removing images was the most effective.

**Comment by arhik** [comment]
May be we should not be creating 5 images. May be 3 is enough. Lets hope that helps. As far I know dockers works by layer of snapshots. So this could be least effective if creating extras images has no overhead.
