### ISSUE TITLE
Less than 5 model points persists after changing files

### ISSUE THREAD

**Issue by RichardMuri** [LanceFiondella/srt.core#36]
If a data set with fewer than five points is uploaded, it grays out tab 1 and gives an error message. If a new, correct file is subsequently uploaded, it does not get rid of the error message. I can post screenshots later today.

**Comment by vshekar** [comment]
Hi Richard


The app is not supposed to handle fewer than 5 points and after the error message the user is expected to reload the app (refresh the page) before uploading a new file.


Shekar

________________________________

**Comment by RichardMuri** [comment]
Perhaps this expectation should be indicated to the user somewhere? It's certainly not a high priority change though
