### ISSUE TITLE
Predicting number of failures for a given time hard coded

### ISSUE THREAD

**Issue by RichardMuri** [LanceFiondella/srt.core#38]
From the first few lines of utility/prediction/Detailed_prediction.R:

```r
get_prediction_k <- function(model,params, t_offset,tn,n){
	# ! -----> #print(">>>>>>>>>")
	# ! -----> #print(params)
	if("JM_N0" %in% names(params)){
		est_faults <- JM_MVF_cont(params,tn + t_offset) - JM_MVF_cont(params,tn)
	}
	else if("GM_D0" %in% names(params)){
		est_faults <- GM_MVF_cont(params,tn + t_offset) - GM_MVF_cont(params,tn)
	}
	else if("GO_aMLE" %in% names(params)){
		est_faults <- GO_MVF_cont(params,tn + t_offset) - GO_MVF_cont(params,tn)
	}
	else if("DSS_aMLE" %in% names(params)){
		est_faults <- DSS_MVF_cont(params,tn + t_offset) - DSS_MVF_cont(params,tn)
	}
	else if("Wei_aMLE" %in% names(params)){
		est_faults <- Wei_MVF_cont(params,tn + t_offset) - Wei_MVF_cont(params,tn)
	}
	else{
		est_faults <- "Not Implemented"
	}
```
Predictions about number of failures for a given time period are hard coded to models at the moment. This should be changed in order to support the addition of new models.

**Comment by RichardMuri** [comment]
![image](https://user-images.githubusercontent.com/11636785/27889044-a4cb40e8-619e-11e7-98d2-169c21c33522.png)

Note that above included models such as the Jelinski-Moranda provide an estimate for failure number, whereas the non-default Musa-Okumoto has a hard coded string.

**Comment by vshekar** [comment]
@RichardMuri , the issue has been solved in the develop branch as shown [here](https://github.com/LanceFiondella/srt.core/blob/develop/utility/prediction/Detailed_prediction.R#L1-L12)

If you'd like you can copy and paste that function to your local code. Or you can use the develop branch, it has a number of significant changes (code should be easier to read and includes FC models among other things) and is fairly stable.
